// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecureService_SecureEcho_FullMethodName = "/SecureService/SecureEcho"
)

// SecureServiceClient is the client API for SecureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureServiceClient interface {
	SecureEcho(ctx context.Context, in *EncryptedRequest, opts ...grpc.CallOption) (*EncryptedResponse, error)
}

type secureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureServiceClient(cc grpc.ClientConnInterface) SecureServiceClient {
	return &secureServiceClient{cc}
}

func (c *secureServiceClient) SecureEcho(ctx context.Context, in *EncryptedRequest, opts ...grpc.CallOption) (*EncryptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedResponse)
	err := c.cc.Invoke(ctx, SecureService_SecureEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecureServiceServer is the server API for SecureService service.
// All implementations must embed UnimplementedSecureServiceServer
// for forward compatibility.
type SecureServiceServer interface {
	SecureEcho(context.Context, *EncryptedRequest) (*EncryptedResponse, error)
	mustEmbedUnimplementedSecureServiceServer()
}

// UnimplementedSecureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecureServiceServer struct{}

func (UnimplementedSecureServiceServer) SecureEcho(context.Context, *EncryptedRequest) (*EncryptedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureEcho not implemented")
}
func (UnimplementedSecureServiceServer) mustEmbedUnimplementedSecureServiceServer() {}
func (UnimplementedSecureServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureServiceServer will
// result in compilation errors.
type UnsafeSecureServiceServer interface {
	mustEmbedUnimplementedSecureServiceServer()
}

func RegisterSecureServiceServer(s grpc.ServiceRegistrar, srv SecureServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecureService_ServiceDesc, srv)
}

func _SecureService_SecureEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureServiceServer).SecureEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureService_SecureEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureServiceServer).SecureEcho(ctx, req.(*EncryptedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecureService_ServiceDesc is the grpc.ServiceDesc for SecureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SecureService",
	HandlerType: (*SecureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SecureEcho",
			Handler:    _SecureService_SecureEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
